### PR TITLE
avoid returning WWW-Authenticate header if challenged by an ajax request

### PR DESCRIPTION
**Pull request by valeriob**
Hi,
with this pull request we avoid to show a popup to users as consequence of an unauthenticated ajax request.

### CODE REVIEW

**Comment by msmolka** [comment]
Hello,
Thanks for PR. It looks useful, but I would like to make it configurable with default off and unit test to check all is correct. Also update readme as well.

**Comment by valeriob** [comment]
Cool, there you go !

**Comment by msmolka** [comment]
@valeriob I've merged the request, but slightly change naming and code structure.

**Comment by valeriob** [comment]
Cool thanks ! do you mind to push a release also ?

**Comment by msmolka** [comment]
Had issues with push, fixed now. New nuget released as well.

**Pull request merged**
